apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: longhorn-tls
  namespace: longhorn-system
spec:
  secretName: longhorn-tls
  dnsNames:
    - "lh.gilded.lan"
  issuerRef:
    name: selfsigned-issuer