
- hosts: localhost
  become: no
  throttle: 1
  tasks:

    # Drain and delete passed nodes -- We could do this with the entire cluster,
    # when deleting the cluster, but when deleting the cluster... it doesn't matter.
    - name: Drain Node before terminating
      when: killhosts is defined
      kubernetes.core.k8s_drain:
        state: drain
        name: "{{ item }}"
        delete_options:
          wait_timeout: 0
          wait_sleep: 5
          ignore_daemonsets: yes
          disable_eviction: yes
          terminate_grace_period: 5
          force: yes
      loop: "{{ killhosts.split(',') }}"
      failed_when: false
    - name: Delete Node
      when: killhosts is defined
      kubernetes.core.k8s:
        api_version: v1
        name: "{{ item }}"
        kind: Node
        state: absent
      loop: "{{ killhosts.split(',') }}"

- hosts: workers
  become: yes
  tasks:
    - name: unistall k3s from nodes
      when: ( killhosts is undefined ) or ( inventory_hostname is in killhosts )
      shell: /usr/local/bin/k3s-agent-uninstall.sh
      ignore_errors: yes

- hosts: masters
  become: yes
  tasks:
    - name: unistall k3s from masters
      when: ( killhosts is undefined ) or ( inventory_hostname is in killhosts )
      shell: /usr/local/bin/k3s-uninstall.sh
      ignore_errors: yes

- hosts: localhost
  become: no
  tasks:
    - name: 'Remove created tokens'
      file:
        path: "~/.HAB/{{ item }}"
        state: absent
      loop:
        - vault-node-token
        - vault-server-token
      when: killhosts is undefined
