- name: Add Cert Manager repo
  kubernetes.core.helm_repository:
    name: jetstack
    repo_url: "https://charts.jetstack.io"
- name: Install Cert Manager
  kubernetes.core.helm:
    update_repo_cache: yes
    name: cert-manager
    namespace: cert-manager
    create_namespace: yes
    chart_ref: jetstack/cert-manager
    wait: yes
    values:
      installCRDs: true
- name: Install cluster issuer certificate
  kubernetes.core.k8s:
    state: present
    wait: yes
    definition:
      apiVersion: cert-manager.io/v1
      kind: ClusterIssuer
      metadata:
        name: selfsigned-issuer
      spec:
        selfSigned: {}
