# Occasionally, the sources drop out and updates stall
- name: Make sure sources.list has extra options
  lineinfile:
    path: /etc/apt/sources.list
    line: "{{ item }}"
  with_items:
    - "deb http://http.us.debian.org/debian/ bullseye main contrib non-free"
    - "deb http://deb.debian.org/debian-security bullseye-security main contrib non-free"
    - "deb http://http.us.debian.org/debian/ bullseye-updates main contrib non-free"

# Add useful MOTD message
- name: Remove Default MOTD
  file:
    path: "{{ item }}"
    state: absent
  loop: [/etc/motd, /etc/update-motd.d/10-uname]
- name: Modify sshd config
  lineinfile:
    path: /etc/ssh/sshd_config
    search_string: "#PrintLastLog yes"
    line: "PrintLastLog no"
- name: Add welcome message
  copy:
    dest: /etc/update-motd.d/10-welcome
    mode: +x
    content: |
      #!/bin/bash
      #clear
      # H/t: https://github.com/ar51an/raspberrypi-motd/blob/main/update-motd.d/10-welcome

      # Greetings
      greetings=" Welcome » $(logname)\n"
      greetings="$greetings $(date +"%a %b %d %Y, %I:%M:%S %p")\n\n"
      greetings="$greetings $(uname -srm)"

      # Device Info
      deviceLabel=" $(tr -d '\0' < /sys/firmware/devicetree/base/model) "

      # Print
      echo -e "\n$greetings"
      echo -e "$deviceLabel"
- name: Add system info message
  copy:
    dest: /etc/update-motd.d/15-system
    mode: +x
    content: |
      #!/bin/bash
      #h/t: https://github.com/ar51an/raspberrypi-motd/blob/main/update-motd.d/15-system

      function sec2time (){
        local input=$1

        ((days=input/86400))
        ((input=input%86400))
        ((hours=input/3600))
        ((input=input%3600))
        ((mins=input/60))

        local daysPlural="s"
        local hoursPlural="s"
        local minsPlural="s"

        if [[ $days -eq 1 ]]; then
          daysPlural=""
        fi
        if [[ $hours -eq 1 ]]; then
          hoursPlural=""
        fi
        if [[ $mins -eq 1 ]]; then
          minsPlural=""
        fi
        echo "$days day$daysPlural $hours hr$hoursPlural $mins min$minsPlural"
      }

      # Last Login
      read loginIP loginDate <<< $(last $(logname) --time-format iso -2 | awk 'NR==1 { print $3,$4 }')
      if [[ $loginDate == *T* ]]; then
        login="$(date -d $loginDate +"%a %b %d %Y, %I:%M %p") » $loginIP"
      else
        # First Login
        login="None"
      fi

      # Stats
      label1="Last ····› $login"
      label2="Temp ···› $(vcgencmd measure_temp | cut -c "6-9")°C"
      label3="Uptime ··› $(sec2time $(cut -d "." -f 1 /proc/uptime)) » $(date -d "@"$(grep btime /proc/stat | cut -d " " -f 2) +"%m-%d-%y %H:%M")"
      label4="Load ···› $(awk '{print $1}' /proc/loadavg)"
      label5="Disk ····› $(df -h ~ | awk 'NR==2 { printf "%sB / %sB » Free: %sB",$3,$2,$4; }')"
      label6="Procs ··› $(/bin/ls -d /proc/[0-9]* | wc -l)"
      label7="Memory ··› $(free -h --si | awk 'NR==2 { printf "%sB / %sB » Free: %sB",$3,$2,$4; }')"
      label8="IP ·····› $(hostname -I)"

      # Print
      echo
      echo -e "                                                         $label2\r   $label1"
      echo -e "                                                         $label4\r   $label3"
      echo -e "                                                         $label6\r   $label5"
      echo -e "                                                         $label8\r   $label7"
- name: Create blank file
  file:
    path: /etc/update-motd.d/20-update
    state: touch
    mode: +x
  changed_when: false
- name: Create directory
  file:
    path: /etc/update-motd-static.d/
    state: directory
- name: Add system info message
  copy:
    dest: /etc/update-motd-static.d/20-update
    mode: +x
    content: |
      #!/bin/bash
      # h/t: https://github.com/ar51an/raspberrypi-motd/blob/main/update-motd.d/15-system

      function msgFormat (){
        local packagesPlural="s"
        if [[ $1 -eq 1 ]]; then
          packagesPlural=""
        fi
        echo "package$packagesPlural"
      }

      # Count
      sudo apt-get update --quiet=2
      pkgCount="$(apt-get -s dist-upgrade | grep -Po '^\d+(?= upgraded)')"

      # Message
      updateMsg=" » $pkgCount $(msgFormat $pkgCount) can be upgraded"

      # Output To Dynamic File
      OUT="/etc/update-motd.d/"$(basename $0)
      exec >${OUT}
      #
      echo "#!/bin/bash"
      echo "####################################################"
      echo "#             DO NOT EDIT THIS FILE                #"
      echo "# EDIT [20-update] In [/etc/update-motd-static.d/] #"
      echo "####################################################"
      #
      echo "cat <<EOF"
      echo -e "\n$updateMsg"
      echo "EOF"
- name: Add cron job
  cron:
    name: Get update count
    job: run-parts /etc/update-motd-static.d
    hour: 3
    minute: 0

# Ensure appropriate cgroups
# Hat tip: https://github.com/anthares101/k3s-pi-cluster/blob/main/roles/install-k3s-workers/tasks/main.yaml
- name: If appropriate cgroups are not in cmdline.txt, add them
  replace:
    path: /boot/cmdline.txt
    regexp: '^([\w](?!.*\b{{ item }}\b).*)$'
    replace: '\1 {{ item }}'
  with_items:
    - "cgroup_enable=cpuset"
    - "cgroup_memory=1"
    - "cgroup_enable=memory"

# Fix raspberry resources
# Hat tip: https://github.com/geerlingguy/ansible-role-raspberry-pi/blob/master/defaults/main.yml
- name: Set the gpu memory to 16mb
  lineinfile:
    dest: /boot/config.txt
    regexp: "^#?gpu_mem"
    line: "gpu_mem=16"
    insertafter: EOF
    state: present
- name: Configure options in /etc/rc.local
  lineinfile:
    dest: /etc/rc.local
    regexp: "^/usr/bin/tvservice"
    line: "/usr/bin/tvservice -o"
    insertbefore: "^exit"
    state: present

# Fix iptables
# Hat Tip: https://github.com/k3s-io/k3s-ansible/blob/master/roles/raspberrypi/tasks/prereq/Raspbian.yml
- name: Flush iptables
  iptables:
    flush: yes
  changed_when: false   # iptables flush always returns changed
- name: Correct iptables legacy versioning - ipv4
  community.general.alternatives:
    name: iptables
    path: /usr/sbin/iptables-legacy
- name: Correct iptables legacy versioning - ipv6
  community.general.alternatives:
    name: ip6tables
    path: /usr/sbin/ip6tables-legacy

######################
# # Maybe do this?
# # https://github.com/k3s-io/k3s-ansible/blob/master/roles/prereq/tasks/main.yml
# #- name: Enable IPv4 forwarding
# #  sysctl:
#     name: net.ipv4.ip_forward
#     value: "1"
#     state: present
#     reload: yes
# - name: Enable IPv6 forwarding
#   when: ansible_all_ipv6_addresses
#   sysctl:
#     name: net.ipv6.conf.all.forwarding
#     value: "1"
#     state: present
#     reload: yes
#######################